name: android_receiver
description: Android Receiver for Remote Control App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  torch_light: ^1.0.0
  vibration: ^3.1.4
  audioplayers: ^5.2.1
  uuid: ^4.0.0
  permission_handler: ^11.0.0
  wakelock_plus: ^1.4.0
  flutter_foreground_task: ^8.0.0
  async_wallpaper: ^2.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/wallpapers/
